sudo: false  # go Docker!
language: python
python:
  - "2.6"
  - "2.7"
env:
  - DEPS='Django<1.5'
  - DEPS='Django<1.6'
  - DEPS='Django<1.7'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
install:
  - pip install $DEPS
  - python setup.py develop
script:
  - python setup.py test
