language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.20
  - DJANGO_VERSION=1.5.12
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install Django==$DJANGO_VERSION django-classy-tags>=0.3.0 selenium
script:
  - python setup.py test
